# NUMPY

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. 

### numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)


dtype-> datatype;
copy-> 'true' b default;
order-> 'C' for row major, 'F' for column major, 'A' for any(default);
ndmin-> dimensionality;

In [37]:
import numpy as np
arr1=np.array([1,2,3])#one-dimensional
print("arr1= ",arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print("arr2= ",arr2)
arr3=np.array([[1,2],[3,4],[7,8]])
print("arr3= ",arr3)
arr4=np.array([1,2,3],dtype=str)
print("arr4= ",arr4)
arr5=np.asarray(arr1,float)
print("arr5= ",arr5)

('arr1= ', array([1, 2, 3]))
('arr2= ', array([[1, 2, 3],
       [4, 5, 6]]))
('arr3= ', array([[1, 2],
       [3, 4],
       [7, 8]]))
('arr4= ', array(['1', '2', '3'], dtype='|S1'))
('arr5= ', array([1., 2., 3.]))


In [17]:
print(arr3.ndim) #number of axes of the array
print(arr3.shape) #row by column dimensionality
print(arr3.size) #arra length
print(arr3.dtype) #datatype
print(arr3.itemsize) #size in bytes, 32/8=4
print(arr3.data) #buffer address
print(type(arr3))

2
(3, 2)
6
int64
8

<type 'numpy.ndarray'>


## Creating arrays of 1s/ 0s

In [18]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2,2), dtype=complex)

array([[1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j]])

In [20]:
np.empty((3,3)) #the function empty creates an array whose initial content is random and depends on the state of the memory

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

## To create a sequence of numbers as array

In [21]:
np.arange(10,30,5) #range from 10 till 30 stepped up by 5

array([10, 15, 20, 25])

In [22]:
np.arange(0.2,1.0,0.2)

array([0.2, 0.4, 0.6, 0.8])

In [23]:
np.arange(1,2,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [24]:
np.linspace(0,2,9) #equally divides the range and outputs(3rd param), number of values as mentioned

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [26]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr=np.arange(8).reshape(2,2,2)
print(arr)
print(arr.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


## Basic Operations

In [28]:
a=np.array([10,20,30,40])
b=np.arange(4)
c=a-b
print(c)
print(c**2)
print(2*a)
print(b/a)
print(100*np.sin(a))
print(a<30)

[10 19 28 37]
[ 100  361  784 1369]
[20 40 60 80]
[0 0 0 0]
[-54.40211109  91.29452507 -98.80316241  74.51131605]
[ True  True False False]


In [29]:
a=np.array([[1,1],[1,2]])
b=np.array([[1,2],[2,3]])
print(a*b)#elementwise product
#print(a@b)#matrix multiplication product
print(a.dot(b))#matrix multiplication product

[[1 2]
 [2 6]]
[[3 5]
 [5 8]]


In [30]:
a=np.random.random((3,3))
print(a)
b=np.ones((3,3))
print(b)

[[0.73537131 0.18621237 0.00172191]
 [0.47568902 0.83920231 0.316869  ]
 [0.55099743 0.05411592 0.5248182 ]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
a+=b
print(a)
#b+=a -> causes error as int has to be upcasted to float explicitly
print(a.sum())
print(a.min())
print(a.max())
print(a.sum(axis=0))#sum of each column
print(a.sum(axis=1))#sum of each row
print(a.min(axis=1))#minimum of each row
print(a.cumsum(axis=1))#cumulative sum o each row
print(a.cumsum())

[[1.73537131 1.18621237 1.00172191]
 [1.47568902 1.83920231 1.316869  ]
 [1.55099743 1.05411592 1.5248182 ]]
12.684997471852597
1.0017219114667042
1.8392023079194662
[4.76205776 4.0795306  3.84340912]
[3.9233056  4.63176032 4.12993155]
[1.00172191 1.316869   1.05411592]
[[1.73537131 2.92158368 3.9233056 ]
 [1.47568902 3.31489132 4.63176032]
 [1.55099743 2.60511335 4.12993155]]
[ 1.73537131  2.92158368  3.9233056   5.39899461  7.23819692  8.55506592
 10.10606335 11.16017927 12.68499747]


## Universal Functions

In [32]:
a=np.array([1,4,9])
print(np.sqrt(a))
print(np.add(np.exp(a),np.sin(a)))

[1. 2. 3.]
[3.55975281e+00 5.38413475e+01 8.10349605e+03]


## Indexing,Slicing,Iterating

In [33]:
a=np.arange(10)**3
print(a)
print(a[2:7])
print(a[::-1])
print(a[:6:2])
print(a[8::-1])

[  0   1   8  27  64 125 216 343 512 729]
[  8  27  64 125 216]
[729 512 343 216 125  64  27   8   1   0]
[ 0  8 64]
[512 343 216 125  64  27   8   1   0]


In [34]:
for i in a:
    print(i**(1/3.)) #taking cuberoot

0.0
1.0
2.0
3.0
3.9999999999999996
4.999999999999999
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [35]:
def f(x,y):
    return 10*x+y

b=np.fromfunction(f,(2,2),dtype=int)
print(b)
print(b[0][1])
print(b[0,1])
print(b[0:2,1])#printing all the elements in 2nd column
print(b[0:2,:])#printing each column in the 1st and 2nd row
print(b[-1])#printing last row

[[ 0  1]
 [10 11]]
1
1
[ 1 11]
[[ 0  1]
 [10 11]]
[10 11]


The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

x[1,2,...] is equivalent to x[1,2,:,:,:],
x[...,3] to x[:,:,:,:,3] and
x[4,...,5,:] to x[4,:,:,5,:].

In [40]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'