# NUMPY

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. 

### numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)


dtype-> datatype;
copy-> 'true' b default;
order-> 'C' for row major, 'F' for column major, 'A' for any(default);
ndmin-> dimensionality;

In [27]:
import numpy as np
arr1=np.array([1,2,3])#one-dimensional
print("arr1= ",arr1)
arr2=np.array([[1,2,3],[4,5,6]])
print("arr2= ",arr2)
arr3=np.array([[1,2],[3,4],[7,8]])
print("arr3= ",arr3)
arr4=np.array([1,2,3],dtype=str)
print("arr4= ",arr4)

arr1=  [1 2 3]
arr2=  [[1 2 3]
 [4 5 6]]
arr3=  [[1 2]
 [3 4]
 [7 8]]
arr4=  ['1' '2' '3']


In [33]:
print(arr3.ndim) #number of axes of the array
print(arr3.shape) #row by column dimensionality
print(arr3.size) #arra length
print(arr3.dtype) #datatype
print(arr3.itemsize) #size in bytes, 32/8=4
print(arr3.data) #buffer address
print(type(arr3))

2
(3, 2)
6
int32
4
<class 'numpy.ndarray'>


## Creating arrays of 1s/ 0s

In [34]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [37]:
np.ones((2,2), dtype=complex)

array([[ 1.+0.j,  1.+0.j],
       [ 1.+0.j,  1.+0.j]])

In [38]:
np.empty((3,3)) #the function empty creates an array whose initial content is random and depends on the state of the memory

array([[  0.00000000e+000,   2.45056560e-321,   2.47032823e-323],
       [  8.17604177e-312,   0.00000000e+000,   6.47616308e-319],
       [  8.17603304e-312,   0.00000000e+000,   2.47032823e-323]])

## To create a sequence of numbers as array

In [42]:
np.arange(10,30,5) #range from 10 till 30 stepped up by 5

array([10, 15, 20, 25])

In [43]:
np.arange(0.2,1.0,0.2)

array([ 0.2,  0.4,  0.6,  0.8])

In [44]:
np.arange(1,2,0.1)

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9])

In [45]:
np.linspace(0,2,9) #equally divides the range and outputs(3rd param), number of values as mentioned

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [46]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [47]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
arr=np.arange(8).reshape(2,2,2)
print(arr)
print(arr.ndim)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3


## Basic Operations

In [55]:
a=np.array([10,20,30,40])
b=np.arange(4)
c=a-b
print(c)
print(c**2)
print(2*a)
print(b/a)
print(100*np.sin(a))
print(a<30)

[10 19 28 37]
[ 100  361  784 1369]
[20 40 60 80]
[ 0.          0.05        0.06666667  0.075     ]
[-54.40211109  91.29452507 -98.80316241  74.51131605]
[ True  True False False]


In [57]:
a=np.array([[1,1],[1,2]])
b=np.array([[1,2],[2,3]])
print(a*b)#elementwise product
print(a@b)#matrix multiplication product
print(a.dot(b))#matrix multiplication product

[[1 2]
 [2 6]]
[[3 5]
 [5 8]]
[[3 5]
 [5 8]]


In [64]:
a=np.random.random((3,3))
print(a)
b=np.ones((3,3))
print(b)

[[ 0.90185177  0.76381107  0.74161751]
 [ 0.78208764  0.50052447  0.09588772]
 [ 0.65412001  0.47828381  0.13267988]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [73]:
a+=b
print(a)
#b+=a -> causes error as int has to be upcasted to float explicitly
print(a.sum())
print(a.min())
print(a.max())
print(a.sum(axis=0))#sum of each column
print(a.sum(axis=1))#sum of each row
print(a.min(axis=1))#minimum of each row
print(a.cumsum(axis=1))#cumulative sum o each row
print(a.cumsum())

[[ 9.90185177  9.76381107  9.74161751]
 [ 9.78208764  9.50052447  9.09588772]
 [ 9.65412001  9.47828381  9.13267988]]
86.0508638902
9.0958877152
9.90185177138
[ 29.33805943  28.74261935  27.97018511]
[ 29.40728035  28.37849983  28.26508371]
[ 9.74161751  9.09588772  9.13267988]
[[  9.90185177  19.66566284  29.40728035]
 [  9.78208764  19.28261212  28.37849983]
 [  9.65412001  19.13240382  28.26508371]]
[  9.90185177  19.66566284  29.40728035  39.18936799  48.68989247
  57.78578018  67.43990019  76.91818401  86.05086389]


## Universal Functions

In [80]:
a=np.array([1,4,9])
print(np.sqrt(a))
print(np.add(np.exp(a),np.sin(a)))

[ 1.  2.  3.]
[  3.55975281e+00   5.38413475e+01   8.10349605e+03]


## Indexing,Slicing,Iterating

In [90]:
a=np.arange(10)**3
print(a)
print(a[2:7])
print(a[::-1])
print(a[:6:2])
print(a[8::-1])

[  0   1   8  27  64 125 216 343 512 729]
[  8  27  64 125 216]
[729 512 343 216 125  64  27   8   1   0]
[ 0  8 64]
[512 343 216 125  64  27   8   1   0]


In [91]:
for i in a:
    print(i**(1/3.)) #taking cuberoot

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0


In [102]:
def f(x,y):
    return 10*x+y

b=np.fromfunction(f,(2,2),dtype=int)
print(b)
print(b[0][1])
print(b[0,1])
print(b[0:2,1])#printing all the elements in 2nd column
print(b[0:2,:])#printing each column in the 1st and 2nd row
print(b[-1])#printing last row

[[ 0  1]
 [10 11]]
1
1
[ 1 11]
[[ 0  1]
 [10 11]]
[10 11]


The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

x[1,2,...] is equivalent to x[1,2,:,:,:],
x[...,3] to x[:,:,:,:,3] and
x[4,...,5,:] to x[4,:,:,5,:].